<#
.SYNOPSIS
    Sets up local development secrets, GitHub Secrets, and Bicep parameters
    from a single config.ps1 file.

.DESCRIPTION
    Reads config.ps1 (not committed) and applies values to:
      -Secrets  dotnet user-secrets for local development
      -GitHub   GitHub repository secrets via gh CLI
      -Bicep    Generates infra/main.local.bicepparam
      -All      All three targets

.EXAMPLE
    .\setup.ps1 -All
    .\setup.ps1 -Secrets
    .\setup.ps1 -GitHub
    .\setup.ps1 -Bicep

.NOTES
    Requires: GitHub CLI (gh) for -GitHub flag.
    Install:  winget install GitHub.cli
#>
param(
    [switch]$Secrets,
    [switch]$GitHub,
    [switch]$Bicep,
    [switch]$All
)

# ---------------------------------------------------------------------------
# Load config
# ---------------------------------------------------------------------------
$configPath = Join-Path $PSScriptRoot "config.ps1"
if (-not (Test-Path $configPath)) {
    Write-Host "config.ps1 not found." -ForegroundColor Red
    Write-Host "Copy config.example.ps1 to config.ps1 and fill in your values." -ForegroundColor Yellow
    exit 1
}
. $configPath

# ---------------------------------------------------------------------------
# 1. dotnet user-secrets
# ---------------------------------------------------------------------------
if ($Secrets -or $All) {
    Write-Host "Setting dotnet user-secrets..." -ForegroundColor Yellow
    $project = "src/BrandsAdvisory/BrandsAdvisory.csproj"

    dotnet user-secrets set "AzureAd:TenantId"                                        $config.TenantId             -p $project
    dotnet user-secrets set "AzureAd:ClientId"                                        $config.ClientId             -p $project
    dotnet user-secrets set "AzureAd:ClientCertificates:0:KeyVaultUrl"                "https://$($config.KeyVaultName).vault.azure.net" -p $project
    dotnet user-secrets set "AzureAd:ClientCertificates:0:KeyVaultCertificateName"    $config.CertName             -p $project
    dotnet user-secrets set "CosmosDb:EndpointUri"                                    $config.CosmosEndpointUri    -p $project
    dotnet user-secrets set "CosmosDb:DatabaseId"                                     $config.CosmosDatabaseId     -p $project
    dotnet user-secrets set "CosmosDb:ContainerName"                                  $config.CosmosContainerName  -p $project
    dotnet user-secrets set "Storage:BlobEndpoint"                                    $config.StorageBlobEndpoint  -p $project
    dotnet user-secrets set "Syncfusion:LicenseKey"                                   $config.SyncfusionLicenseKey -p $project

    Write-Host "dotnet user-secrets set." -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# 2. GitHub Secrets via gh CLI
# ---------------------------------------------------------------------------
if ($GitHub -or $All) {
    Write-Host "Setting GitHub Secrets..." -ForegroundColor Yellow

    gh secret set AZURE_CLIENT_ID        --body $config.AzureClientId
    gh secret set AZURE_SUBSCRIPTION_ID  --body $config.SubscriptionId
    gh secret set AZURE_RESOURCE_GROUP   --body $config.ResourceGroup
    gh secret set AZURE_WEBAPP_NAME      --body $config.AppName
    gh secret set APP_NAME               --body $config.AppName
    gh secret set PLAN_NAME              --body $config.PlanName
    gh secret set COSMOS_ACCOUNT_NAME    --body $config.CosmosAccountName
    gh secret set COSMOS_DATABASE_ID     --body $config.CosmosDatabaseId
    gh secret set COSMOS_CONTAINER_NAME  --body $config.CosmosContainerName
    gh secret set KEY_VAULT_NAME         --body $config.KeyVaultName
    gh secret set CERT_NAME              --body $config.CertName
    gh secret set CLIENT_ID              --body $config.ClientId
    gh secret set TENANT_ID              --body $config.TenantId
    gh secret set SYNCFUSION_LICENSE_KEY --body $config.SyncfusionLicenseKey
    gh secret set STORAGE_ACCOUNT_NAME   --body $config.StorageAccountName

    Write-Host "GitHub Secrets set." -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# 3. Generate infra/main.local.bicepparam
# ---------------------------------------------------------------------------
if ($Bicep -or $All) {
    Write-Host "Generating infra/main.local.bicepparam..." -ForegroundColor Yellow

    $content = @"
// ---------------------------------------------------------------------------
// main.local.bicepparam — generated by setup.ps1, do not commit
// ---------------------------------------------------------------------------
using './main.bicep'

param appName               = '$($config.AppName)'
param planName              = '$($config.PlanName)'
param cosmosAccountName     = '$($config.CosmosAccountName)'
param cosmosDatabaseId      = '$($config.CosmosDatabaseId)'
param cosmosContainerName   = '$($config.CosmosContainerName)'
param keyVaultName          = '$($config.KeyVaultName)'
param keyVaultCertificateName = '$($config.CertName)'
param tenantId              = '$($config.TenantId)'
param clientId              = '$($config.ClientId)'
param syncfusionLicenseKey  = '$($config.SyncfusionLicenseKey)'
param storageAccountName    = '$($config.StorageAccountName)'
"@

    $outputPath = Join-Path $PSScriptRoot "infra/main.local.bicepparam"
    Set-Content -Path $outputPath -Value $content -Encoding UTF8

    Write-Host "infra/main.local.bicepparam generated." -ForegroundColor Green
}

Write-Host "Done." -ForegroundColor Green
